// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdbomgthptitamfppehw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYm9tZ3RocHRpdGFtZnBwZWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODM0NzgsImV4cCI6MjA2MDI1OTQ3OH0.M0tx0aBx30EzeZbs28FznLGeQ00eoLDvirpl9Zg7xXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);